# SNAP-SHOOT - SECRETS

#CHATGPT
OPENAI_API_KEY = "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"
ORGANIZATION_ID = "org-S6hG2xydQF8XwcexPJtyE0q3"

#NEWS 
#EXA
EXA_API_KEY="2ef75169-61f4-4a0e-8954-c827e60a9638"

#NEWS API
NEWS_API_KEY="92e3d5fd13b747f8826e7c5bac1aa5f6"

#NEWSDATA.IO

NEWSDATA_API_KEY="pub_4390660ae930b8573f92ad3b70eec606c6a36"

WORLDNEWS_API_KEY="20abf312b9d84bbf83eea639ac72676f"
#SERPER
SERPER_API_KEY = "bc1ad0594b248f927d16c9b2faf1dff7f1e84cac"
SERPAPI_KEY = "4bc71d074ec73d9371a9c3e8f0f2874c3666d2cc5967a08c308125d672324423"
#Google
GOOGLE_API_KEY = "AIzaSyBSdTi5LJs_YJF9oGAOTbvjvmMTqP-E3L4"
GOOGLE_CSE_ID = "d5ef5fcef360d4fbe"

#TAVILY
TAVILY_API_KEY = "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"

#huggingface
HF_API_KEY = "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"
