# SNAP-SHOOT - SECRETS

#CHATGPT
OPENAI_API_KEY = "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"
ORGANIZATION_ID = "org-S6hG2xydQF8XwcexPJtyE0q3"

#EXA
EXA_API_KEY="2ef75169-61f4-4a0e-8954-c827e60a9638"

#SERPER
SERPER_API_KEY = "bc1ad0594b248f927d16c9b2faf1dff7f1e84cac"

#Google
GOOGLE_API_KEY = "AIzaSyBSdTi5LJs_YJF9oGAOTbvjvmMTqP-E3L4"
GOOGLE_CSE_ID = "d5ef5fcef360d4fbe"

#TAVILY
TAVILY_API_KEY = "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"

#huggingface
HF_API_KEY = "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"
